name: fetch readmes

on: workflow_dispatch

jobs:
  fetch-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch th2-infra
        run: sudo wget https://raw.githubusercontent.com/th2-net/th2-infra/master/README.md -O "./content/readmes/th2-infra.md"
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          message: "Automatic fetch README's" ${{ date +'%Y.%m.%d.%H.%m.%S' }}
          push: true

